"""move CASCADE to child table CartDetail.card_id

Revision ID: 4113ac3870a4
Revises: 87335722527b
Create Date: 2026-03-01 20:49:59.076330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4113ac3870a4'
down_revision: Union[str, Sequence[str], None] = '87335722527b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_detail_table_cart_id_fkey'), 'cart_detail_table', type_='foreignkey')
    op.create_foreign_key(None, 'cart_detail_table', 'cart_table', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_detail_table', type_='foreignkey')
    op.create_foreign_key(op.f('cart_detail_table_cart_id_fkey'), 'cart_detail_table', 'cart_table', ['cart_id'], ['id'])
    # ### end Alembic commands ###
