"""rename constraints in table args Cart

Revision ID: 87335722527b
Revises: 6c4047625314
Create Date: 2026-03-01 20:45:15.018490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87335722527b'
down_revision: Union[str, Sequence[str], None] = '6c4047625314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_migration_logs'), 'cart_detail_table', type_='unique')
    op.create_unique_constraint('cart_detail_cart_product_id', 'cart_detail_table', ['cart_id', 'product_id'])
    op.alter_column('cart_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('cart_table_unique_customer_id', 'cart_table', ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_table_unique_customer_id', 'cart_table', type_='unique')
    op.alter_column('cart_table', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint('cart_detail_cart_product_id', 'cart_detail_table', type_='unique')
    op.create_unique_constraint(op.f('cart_migration_logs'), 'cart_detail_table', ['cart_id', 'product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
