"""added constraints for products in order

Revision ID: 777446601329
Revises: 98b1a97cdb67
Create Date: 2026-03-15 15:34:16.815858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777446601329'
down_revision: Union[str, Sequence[str], None] = '98b1a97cdb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_in_order_product_id'), 'products_in_order', type_='unique')
    op.create_unique_constraint('products_in_order_id_product_id', 'products_in_order', ['product_id', 'order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_in_order_id_product_id', 'products_in_order', type_='unique')
    op.create_unique_constraint(op.f('products_in_order_product_id'), 'products_in_order', ['product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
