"""added constraints, change field parameters

Revision ID: 98b1a97cdb67
Revises: a6a609c7be00
Create Date: 2026-03-15 13:35:51.710075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b1a97cdb67'
down_revision: Union[str, Sequence[str], None] = 'a6a609c7be00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_order_number', 'orders', ['order_number'])
    op.create_unique_constraint('products_in_order_product_id', 'products_in_order', ['product_id'])
    op.drop_constraint(op.f('products_in_order_order_id_fkey'), 'products_in_order', type_='foreignkey')
    op.create_foreign_key(None, 'products_in_order', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_in_order', type_='foreignkey')
    op.create_foreign_key(op.f('products_in_order_order_id_fkey'), 'products_in_order', 'orders', ['order_id'], ['id'])
    op.drop_constraint('products_in_order_product_id', 'products_in_order', type_='unique')
    op.drop_constraint('order_order_number', 'orders', type_='unique')
    # ### end Alembic commands ###
